services:
  ocr:
    image: ocr
    volumes:
      - ocr_cache:/home/appuser/.EasyOCR:z # Persists downloaded EasyOCR models in a named volume
    networks:
      - public-hosting
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 4000M


networks:
  public-hosting:
    external: true

volumes:
  ocr_cache:
